name: ollama-action
description: Run Ollama large language models (LLMs) with GitHub Actions
author: remarkablemark

inputs:
  model:
    description: Language model name
    required: true
  prompt:
    description: Input prompt to generate a response for
    required: true
  version:
    description: Ollama version
    required: false

outputs:
  response:
    description: Generated response message
    value: ${{ steps.llm.outputs.response }}

runs:
  using: composite
  steps:
    - name: Setup Ollama
      uses: ai-action/setup-ollama@v1
      with:
        version: ${{ inputs.version }}

    - name: Run LLM
      id: llm
      shell: bash
      run: |
        EOF=EOF_OLLAMA_$(openssl rand -hex 12)
        {
          echo "response<<$EOF"
          ollama run $MODEL "$(printf '%q' $PROMPT)"
          echo $EOF
        } >> $GITHUB_OUTPUT
      env:
        MODEL: ${{ inputs.model }}
        PROMPT: ${{ inputs.prompt }}

branding:
  icon: terminal
  color: gray-dark
