name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run action
        id: response-1
        uses: ./
        with:
          model: tinyllama
          prompt: What's a large language model?
          cache: true

      - name: Print response 1
        shell: bash
        env:
          response: ${{ steps.response-1.outputs.response }}
        run: echo "$response"

      - name: Run action with multiline prompt
        id: response-2
        uses: ./
        with:
          model: tinyllama
          prompt: |
            Tell me
            a joke.
          version: 0.5.10
          cache: false

      - name: Print response 2
        shell: bash
        env:
          response: ${{ steps.response-2.outputs.response }}
        run: echo "$response"

      - name: Run action
        id: response-3
        uses: ./
        with:
          model: tinyllama
          prompt: |
            # Markdown example

            A markdown example with backticks:

            ```bash
            echo "The time is now $(date +%T)"
            ```

      - name: Print response 3
        shell: bash
        env:
          response: ${{ steps.response-3.outputs.response }}
        run: echo "$response"
